# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 08:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glosy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wazne', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('glosy_na_wybranego_kanydata', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name_plural': 'glosy',
            },
        ),
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('rodzaj', models.CharField(choices=[('W', 'Wieś'), ('M', 'Miasto'), ('Z', 'Zagranica'), ('S', 'Statek')], max_length=30)),
                ('liczba_mieszkancow', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('uprawnieni', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name_plural': 'gminy',
            },
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'kandydaci',
            },
        ),
        migrations.CreateModel(
            name='Karty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('gmina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PKW.Gmina')),
            ],
            options={
                'verbose_name_plural': 'karty',
            },
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nazwa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'wojewodztwa',
            },
        ),
        migrations.AddField(
            model_name='gmina',
            name='wojewodztwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PKW.Wojewodztwo'),
        ),
        migrations.AddField(
            model_name='glosy',
            name='gmina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PKW.Gmina'),
        ),
        migrations.AddField(
            model_name='glosy',
            name='kandydat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PKW.Kandydat'),
        ),
    ]
