# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PKW', '0002_remove_glosy_liczba'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmina',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 21, 14, 56, 26, 261572), null=True),
        ),
    ]
