# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PKW', '0003_gmina_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmina',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
