# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PKW', '0004_auto_20160521_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmina',
            old_name='data',
            new_name='czas',
        ),
    ]
